/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //wrap
  Portal_map: {
    Portal: ["se/index"]
  },

  se_dbms: {
    dbms: [
      { type: "autogenerated", dirName: "se/dbms" },
    ],
  },
  se_middleware: {
    middleware: [
      { type: "autogenerated", dirName: "se/middleware" },
    ],
  },
  se_network: {
    network: [
      { type: "autogenerated", dirName: "se/network" },
    ],
  },
  se_os: {
    os: [
      { type: "autogenerated", dirName: "se/os" },
    ],
  },
  se_programming: {
    programming: [
      { type: "autogenerated", dirName: "se/programming" },
    ],
  },
  se_vcs: {
    vcs: [
      { type: "autogenerated", dirName: "se/vcs" },
    ],
  },
  se_authorization: {
    authorization: [
      { type: "autogenerated", dirName: "se/authorization" },
    ],
  },
  se_crypto: {
    authorization: [
      { type: "autogenerated", dirName: "se/crypto" },
    ],
  },
  //Amateur

  //TreasureMap
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
